services:
  - type: web
    name: yoga-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: yoga-db
          property: connectionString
databases:
  - name: yoga-db
    databaseName: yoga
    user: yoga_user
