BEGIN;

INSERT INTO sitting  (name, img1, img2, img3, notes)
VALUES
    ('Easy Pose', 'https://lh5.googleusercontent.com/DuhWFp7QBpR-X6whKehCvm233FCwqdy-5fjjm0JPlkq6euMSkPohWQbkPRO_-JNHyo-OBjSskRy_6-_hfgZNxLQaSyXFWKHepybaHAaN-yyAOmYUWq4Y2l3m0h5WvayGOL_D-Ina', 'https://www.huggermugger.com/wp-content/uploads/2018/01/sukhasana-meditation.jpg', 'http://arogyayogaschool.com/blog/wp-content/uploads/2017/04/Sukhasana-Help-Reduce-Your-Blood-Pressure.jpg', 'This is one way to do easy pose, but as the name suggests, this pose is intended to be a comfortable seat. If this configuration does not work for you, take any cross-legged position. Sitting on a blanket to elevate the hips is also encouraged here.'),
    ('Thunderbolt Pose', 'https://i.pinimg.com/originals/78/8a/5d/788a5d0c9c852e1cdcd58a8c98fded8b.jpg', 'https://photos.cdn-outlet.com/yo-images/userfiles/guide/image/yoga/yoga_how-to-do-thunderbolt-pose_300x350_jpg.jpg', 'https://i.ytimg.com/vi/3ILEYJOtHgM/maxresdefault.jpg', 'A basic kneeling position, with the seat resting on the feet.'),
    ('Staff Pose', 'https://www.verywellfit.com/thmb/u6DHrDtCYh8JD5-Kh7fQA-EGLcE=/1500x1000/filters:no_upscale():max_bytes(150000):strip_icc()/StaffPose_annotated-007b1534c2914848af88f7e09360c0b4.jpg', 'https://www.ekhartyoga.com/media/images/articles/content/Staff-Pose-Dandasana-Ekhart-Yoga.jpg', 'https://cdn.shopify.com/s/files/1/0032/7539/1011/articles/Yoga_SeatedStaffPose_01_300x350_1_600x.jpg?v=1558424546', 'Staff pose is often called the seated equivalent of mountain pose. Just as mountain sets up the alignment for many standing poses, staff pose is the starting point for many seated poses.'),
    ('Seated Forward Bend', 'https://www.ekhartyoga.com/media/images/articles/content/Paschimottanasana-Seated-Forward-bend-Ekhart-Yoga.jpg', 'https://i.ytimg.com/vi/Xn1wigQSrmI/maxresdefault.jpg', 'https://cdn.drweil.com/wp-content/uploads/2016/12/health-wellness_balanced-living_exercise-fitness_seated-forward-bend-pose_2716x1811_000026479707-600x450.jpg', 'There are several approaches to coming into seated forward bend, but try to keep the back flat as you tip the pelvis forward.'),
    ('Seated Wide Legged Straddle', 'https://i.ytimg.com/vi/GVo52kzskAg/maxresdefault.jpg', 'https://awakenwellness.files.wordpress.com/2012/06/seatedwideleg.jpg', 'https://www.yogateket.com/image/original/Seated-Wide-Angle-Straddle.jpg', 'You do not have to go for a super wide angle with the legs. Feeling some stretch in the inner thigh is common, but you do not need to go for a full split.'),
    ('Cobbler Pose', 'https://www.verywellfit.com/thmb/nBgqjt8A7V3uEceRK2hsiGCiDeg=/1500x1000/filters:no_upscale():max_bytes(150000):strip_icc()/CobblersPose_annotated-b6b590ebb22c4da1948cbd78ff1651d1.jpg', 'https://i.ytimg.com/vi/s5265rtPTMg/maxresdefault.jpg', 'https://asmy.org.au/app/uploads/2016/12/Cobbler-795x455.jpg', 'Cobbler pose can be taken into a forward bend if your groin allows it. Light pressure with your forearms on your legs can intensify the stretch.'),
    ('Half Lord of the Fishes Pose', 'https://www.verywellfit.com/thmb/tVqnwWu8IjsKJNe9CzypK9SYJsE=/1500x1000/filters:no_upscale():max_bytes(150000):strip_icc()/HalfLordOfTheFishes_annotated-d4bb4f3d70f444a5966d2018bbee8564.jpg', 'https://www.ekhartyoga.com/media/image/articles/Ardha-Matsyendrasana-Half-lord-of-the-fishes-yoga-pose.jpg', 'https://www.gaia.com/wp-content/uploads/Meta-Half-Lord-of-fish-1024X576-768x432.jpg', 'Half lord of the fishes is also known as a seated spinal twist. It is important to keep your front foot and sit bones grounded to the floor here so that you have something to anchor the twist. Switch after 30 seconds.'),
    ('Cow Face Pose', 'https://www.verywellfit.com/thmb/syR23KHuv2Tw9apgCyrwuTn-86g=/1500x1000/filters:no_upscale():max_bytes(150000):strip_icc()/CowFacePoseGomukhasana_annotated-49620d2c06104d369a1c5617054500b5.jpg', 'https://i.pinimg.com/originals/83/1f/ea/831fea8661e48fc513da23aaaa7bba53.jpg', 'https://www.ekhartyoga.com/media/images/articles/content/Cow-face-pose-Gomukhasana-Esther-Ekhart-292x292.jpg', 'Cow face pose gets into parts of the shoulders and upper arms that are rarely used by many of us. Do not be surprised to discover that it is much easier to bind the hands on one side than the other. This kind of asymmetry is very common, since most people favor one hand over the other. Switch after 30 seconds.'),
    ('Half Lotus Pose', 'https://www.verywellfit.com/thmb/En6PM_MENqQsh63QmMaLvpMc7XU=/3000x2000/filters:fill(FFDB5D,1)/24-3567080-Half-Lotus-Pose-GIF-36e1c81083ed497387865a51f63d0f13.gif', 'https://beyogi.com/wp-content/uploads/2019/06/Half-Lotus-Pose_Beyogi_yoga-insurance.jpg', 'http://www.yogabasics.com/yogabasics2017/wp-content/uploads/2013/11/half-lotus1.jpg', 'Half lotus is a nice stopping off point on the way to full lotus (see below). Since full lotus can be very hard on the knees, many yoga students prefer this version, which can be used for seated meditation. Switch after 30 seconds'),
    ('Hero Pose', 'https://www.verywellfit.com/thmb/RZHRYIRYiA9x_lmc918k2cIWOLY=/1500x1000/filters:no_upscale():max_bytes(150000):strip_icc()/HeroPose_annotated-c35574995bf4423a9c321ad3cbc9032f.jpg', 'https://www.yogaclassplan.com/wp-content/uploads/2015/11/Heros-Pose.jpg', 'http://cdn.shopify.com/s/files/1/0032/7539/1011/articles/Yoga_How_To_Do_Hero_Pose_300x350_74b88d57-ae39-4705-ac76-8c3dc2f5e2a2_grande.jpg?v=1558424588', 'Hero pose is also a good meditation posture. Some people find it easier to keep the spine erect in this pose than in cross-legged positions when seated for a long time. But for many people who sit at a desk all day, rooting your sits bones on the floor is difficult.'),
    ('Low Boat Pose', 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/BBfcews/_h400_w284_m1_bwhite.jpg', 'https://pocketyoga.com/assets/images/poses/boat_low.png', 'https://mk0yogiapproveddv8to.kinstacdn.com/wp-content/uploads/2018/03/low-boat-pose.jpg', 'Keep abs very engaged, shoulders and legs should be off the ground.'),
    ('Boat Pose', 'https://www.verywellfit.com/thmb/w1L1dooXIv5YExPz043zllQvXYE=/735x0/boat-pose_annotated-9a4effe2ff3e4c9f94dc9371f48e98ab.gif', 'https://www.ekhartyoga.com/media/image/articles/Boat-pose-Navasana-Ekhart-Yoga.jpg', 'https://www.yogajournal.com/wp-content/uploads/sites/17/2009/12/story-image-18479.jpg', 'If you find it difficult to maintain that nice V-shape with your legs straight in boat pose, bend the knees, keeping the shins parallel to the floor. This should help your keep your spine straight and your thighs lifted.'),
    ('Head-to-Knee Pose', 'https://www.verywellfit.com/thmb/rJ6rmPkGUbpJaN0n54jByQnkD1c=/1500x1000/filters:no_upscale():max_bytes(150000):strip_icc()/HeadToKneePose_annotated-4474f9ee5803414eabcfa89995cc8b8e.jpg', 'http://www.yogajournal.com/wp-content/uploads/sites/17/2007/08/yp_292_00990_bjk.jpg', 'http://www.yogajournal.com/wp-content/uploads/sites/17/2015/01/headtoknee-forward-bend-yoga-asana-picture-id471382238.jpg', 'When forward folding in Head-to-Knee Pose, try to align your torso so you are folding over your extended leg rather than the space between your legs. Switch after 30 seconds.'),
    ('Revolved Head to Knee Pose', 'https://i.pinimg.com/originals/19/db/8c/19db8cb3fe0488569d7d182940cedbc7.jpg', 'https://www.yogauonline.com/sites/default/files/styles/wellness_blog_level3_main/public/article_images/633a5062_copy_1500x1000.jpg?itok=r9Nxh1hg', 'https://cdn.beyogi.com/wp-content/uploads/2015/03/Revolved-Head-to-Knee-Parivrtta-Janu-Sirsasana-1024x683.png', 'Students often grab for their big toe in Revolved Head to Knee Pose at the expense of opening the chest to the ceiling. If holding your toe is causing your chest to turn downward, bend your elbow and hold the back of your head instead. Switch after 30 seconds.'),
    ('Half Pidgeon Pose', 'https://dsgmedia.blob.core.windows.net/pub/2018/08/HowToDoHalfPigeonPose.jpg', 'https://pocketyoga.com/assets/images/poses/pigeon_half_L.png', 'https://images.ctfassets.net/p0sybd6jir6r/1W10Y6Pa7sn9j7nxeRl1YH/9f1d6781a2cbc98f1dd288ff4f48ce0e/half-pigeon-pose-set-up-step-5-d948fb269adce7d01f053bb6c8ccfecc.jpg', 'Keep head lifted for this pose, switch sides after 30 seconds'),
    ('Sleeping Pidgeon', 'http://www.yogajournal.com/wp-content/uploads/sites/17/2016/03/yp_282_0141_fnl-sleeping-pigeon-pose-jason-crandell.jpg', 'http://www.yogajournal.com/wp-content/uploads/sites/17/2015/03/201503-blog-pigeon-erin.jpg', 'https://cdn.shopify.com/s/files/1/0040/3098/8386/files/PigeonBlock.jpg', 'Head goes down as far as you can without hurting yourself, go into it slowly. Switch after 30 seconds.'),
    ('Knee to Ankle', 'https://www.verywellfit.com/thmb/No3JPY2wIM8dt5Vz0HYkYXWRXOk=/1500x1000/filters:no_upscale():max_bytes(150000):strip_icc()/KneetoAnklePose_annotated-b51b5b94f6d94cc88555c461811fb092.jpg', 'https://www.verywellfit.com/thmb/ZdmH_PA4jBgKdwjUu6zZpAiOb9A=/1333x1000/smart/filters:no_upscale()/kneetoankle1500-567837ce3df78ccc153421f5.jpg', 'https://kristinmcgee.com/wp-content/uploads/2012/06/tight-hips.jpg', 'Knee to ankle is also called double pigeon and you can see why. Keep the feet flexed and bring the shins as close to parallel as possible to the front of your mat. Switch after 30 seconds.'),
    ('Heron Pose', 'https://www.yogaclassplan.com/wp-content/uploads/2018/02/Heron-pose_Krounchasana-edited.jpg', 'http://www.yogajournal.com/wp-content/uploads/sites/17/2007/08/3yp_289_4829_bjk.jpg', 'https://www.ekhartyoga.com/media/images/articles/content/Heron-Pose-Kronuchasana-Ekhart-Yoga.jpg', 'Like boat pose (see above), it is better to bend your extended knee in heron than to keep it straight and end up with the spine rounded forward. A nice straight spine is more important than a straight leg. Switch after 30 seconds.'),
    ('Marichi Pose', 'https://beyogi.com/wp-content/uploads/2015/03/Marichis-Pose-1-Marichyasana.png', 'https://cdn.doyou.com/wp/2015/08/how-to-do-marichyasana-1-marichis-pose-1.png=w768', 'https://images.squarespace-cdn.com/content/v1/53c723f0e4b057b2aaf90c0f/1414945650937-3L9Z3E0C050GARZP7XVU/ke17ZwdGBToddI8pDm48kJ-TibQGV2ecYXE5_1AtpLJZw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZamWLI2zvYWH8K3-s_4yszcp2ryTI0HqTOaaUohrI8PI8kzgbt7B-g70Qwzw-pRV0yudSlihN9h_DHrHhdp8qTkKMshLAGzx4R3EDFOm1kBS/063-Marichyasana-1-2362.jpg', 'In marichyasana I, make sure that you can take the bind before you start to forward bend. If the bind is not there, stay in an upright position. Switch after 30 seconds.'),
    ('Lotus Pose', 'https://www.verywellfit.com/thmb/uX2gqxsyWmP8bUzvjbGHkqn9aP8=/3000x2000/filters:fill(FFDB5D,1)/23-3567098-LotusPose-006-a297dfb82b274118bfb408406fa3c576.jpg', 'https://imageresizer.static9.net.au/VZS4YIZ7nPy6a9ho-lW9GraLOog=/1200x900/https%3A%2F%2Fprod.static9.net.au%2F_%2Fmedia%2FNetwork%2FImages%2F2017%2F05%2F19%2F14%2F16%2F170519coach_lotus_pose.jpg', 'https://i.pinimg.com/originals/ce/07/db/ce07db0e38d8dbd24376b4d3e3fb704f.jpg', 'Lotus is often thought of as the quintessential yoga pose, but it should be approached with caution by beginners. Switch after 30 seconds.'),
    ('Compass Pose', 'https://www.verywellfit.com/thmb/sMxKFPp5f9V5pSZbsSqLLGW3LMo=/1500x1000/filters:fill(FFDB5D,1)/CompassPose_annotated-f33bf60e8b2f4649b0342e6ed4f36835.jpg', 'http://www.yogajournal.com/wp-content/uploads/sites/17/2015/02/rina-compass-parivrtta-surya-yantrasana.jpg', 'https://www.yogauonline.com/sites/default/files/styles/wellness_blog_level3_main/public/article_images/mccrary_article_photo-seated_compass_pose_photo.jpg?itok=x-DPfLkA', 'If you are the kind of person who can easily throw your leg behind your head, compass pose is going to be right up your alley. Otherwise, there are plenty of other hamstring stretches to work on. Switch after 30 seconds.'),
    ('Monkey Pose', 'https://cdn.doyou.com/wp/2015/06/How-to-do-Hanumanasana-or-Monkey-Pose.jpg=w768', 'https://www.verywellfit.com/thmb/TLKcFUOkjKhd8xtbfh9o2w9ncRk=/3000x2000/filters:fill(FFDB5D,1)/21-3567083-MonkeyPose-002-c9274104880c4566a54e6e05ba9ea2af.jpg', 'https://www.yogateket.com/image/original/splitspose.jpg', 'Unless you have very open hamstrings, work on monkey pose with two or three blocks handy. Use one block under each hand and can slide one under your front thigh for support when you get close enough to the floor. Proceed slowly here to avoid a strain. Switch after 30 seconds.'),
    ('Double Leg Raise Pose', 'https://previews.123rf.com/images/byheaven/byheaven1111/byheaven111100022/11270278-yoga-uttanpadasana-double-leg-raise-pose-by-beautiful-caucasian-woman-in-blue-capri-and-top-at-white.jpg', 'https://wellnessworks.in/wp-content/uploads/2020/06/Uttanpadasana-Variation-double-raised-leg-poses-yoga.jpg', 'https://wellnessworks.in/wp-content/uploads/2020/06/Double-leg-raises-Yoga-Postures-asanas-how-many-a-day-benefits-belly-fat-weight-loss-flexibility.jpg', 'Lie flat on your back with your ankles together and arms at your side with your palms facing down.'),
    ('Reclining Bound Angle or Butterfly Pose', 'https://www.yogajournal.com/wp-content/uploads/sites/17/2007/08/hp_288_13_bjk2.jpg?resize=1024,576', 'https://cdn.doyou.com/wp/2012/12/How-To-Do-Reclined-Bound-Angle-Pose.jpg=w768', 'https://www.ekhartyoga.com/media/images/articles/content/Supta-Baddha-Konasana-Reclined-Butterfly-yoga-pose.jpg', 'Begin by lying flat on our back with your arms outward and your palms facing upward. Bring the heels of your feet together as close to your pelvic area as you feel comfortable. Breathe, relax and let the power of gravity gently lower your knees toward the ground.'),
    ('Wind Relieving Pose', 'http://www.yogabasics.com/yogabasics2017/wp-content/uploads/2013/12/WindRelieve_9846.jpg', 'http://worldpeaceyogaschool.com/blog/wp-content/uploads/2016/09/Wind-Relieving-Pose-1.jpg', 'https://vinyasayogaacademy.com/blog/wp-content/uploads/2020/03/pavanamuktasana.jpg', 'Again, begin lying face up with your ankles together and inhale.With an exhale bend your legs and bring your knees up to your chest. Wrap your arms around your knees to carefully coax them to come closer to your chest. Bring your forehead onto or near to your knees. Be cautious not to strain your neck.'),
    ('Bridge Pose', 'https://www.verywellfit.com/thmb/prD41wP9mBnDFD6Iq2wU07eIqPk=/1500x1000/filters:no_upscale():max_bytes(150000):strip_icc()/SupportedBridgePose_annotated-79c06b222b6846b3b1e467de6fc03250.jpg', 'https://cdn.shopify.com/s/files/1/0032/7539/1011/articles/Yoga_BridgePose_01_300x350_405c42cd-5076-486d-b72f-74b87d07496a_600x.jpg?v=1558424518', 'https://www.gaia.com/wp-content/uploads/Bridge_DaynaSeraye-768x432.jpg', 'As you lie on your back, bend your legs and place your feet directly under your knees. Slowly lift your hips upward toward the sky. You can use your arms to lift and support your lower back or extend them flat as you grab onto your ankles or hold your hands together. Use the muscles in your legs as support and bring your chest toward your chin. If you feel any pressure in your spine, use your hands to support yourself or hold the pose for less time, otherwise, remain here for five breaths.'),
    ('Reclining Spinal Twist', 'https://www.verywellfit.com/thmb/3TEbXpzrpMJwy0A4RlhA3zQCQ04=/1500x844/smart/filters:no_upscale()/Verywell-20-4023748-SpinalTwist01-1729-5995b536845b340010c016cf.gif', 'https://cdn.doyou.com/wp/2013/06/How-To-Do-Reclined-Spinal-Twist-Pose.jpg=w768', 'https://www.yogaclassplan.com/wp-content/uploads/2014/12/reclining-spinal-twist.jpg', 'Lie flat on your back with your arms extended straight out to resemble a cross. Take a deep inhale and then with an exhale, rotate your hips to the left and bring your right leg over your left. Your right leg is bent at a 90 degree angle and your left leg remains extended straight. Place your left hand on your right knee and let the weight and gravity gently bring it closer to the ground. Turn your head to look over at your right extended arm for a gentle and enjoyable spinal twist. Relax and breathe for as long as you’d like in this pose and then repeat the process for the other side. Switch after 30 seconds.'),
    ('Corpse Pose', 'https://www.verywellfit.com/thmb/G-Y5vgWLEB8mGBf5CCMgL4t51wg=/1500x1000/filters:no_upscale():max_bytes(150000):strip_icc()/CorpsePoseSavasana_annotated-40a60cc86f9c41f8851048fd44e7bb4d.jpg', 'http://www.yogajournal.com/wp-content/uploads/sites/17/2007/08/2hp_291_1982_gn_bjk.jpg', 'https://dal8cjxzfqbw.cloudfront.net/wp-content/uploads/2019/01/yoga-Corpse-Pose-SAVASANA.jpg', 'Come to lie face up with your feet on the corners of your mat. Let them drop and point outward. Place your arms out at your side with your palms facing upward. Close your eyes and let your body relax and release all tension from every muscle, every organ, every pore, every molecule… You get the point. Melt and enjoy for as long as you’d like. The longer the better!'),
    ('Happy Baby Pose', 'http://www.yogajournal.com/wp-content/uploads/sites/17/2008/05/3hp_288_14_bjk2.jpg', 'https://post.healthline.com/wp-content/uploads/2020/10/happy-baby-pose-1200x628-facebook-1200x628.jpg', 'https://cdn.prod.openfit.com/uploads/2019/04/28121253/happy-baby-pose-micki-duran-yoga5211-1200x600.jpg', 'If you can’t easily hold your feet with your hands, try holding each foot with a yoga strap looped around the middle arch.'),
    ('Fish Pose', 'https://www.verywellfit.com/thmb/RGeuJ54gNbKXyBBldlLTbbsp-t4=/1500x1000/filters:fill(FFDB5D,1)/fish-pose_annotated-cd6f2e392a67444b9b0c284cc1ba1526.jpg', 'https://cf.ltkcdn.net/yoga/images/orig/192415-509x339-Yoga-fish-pose.jpg', 'https://i.pinimg.com/originals/a4/59/fe/a459fe7aef55edb75722bf9f940d8e92.jpg', 'Go into it slowly, do not strain your back');

COMMIT;